### ISSUE TITLE
Latest update flagged by Windows Defender: Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by Payens** [Nnoggie/MythicDungeonTools#262] opened 2021-08-19 07:10 UTC
The trojan in question is randomware. Why is it flagging it as such?

**Comment by Avabehe** [comment] 2021-08-19 10:50
The same problem here, pls solve it

**Comment by nsc-jens** [comment] 2021-08-19 11:58
Duplicate of #261

Can you run Windows update and install the latest Microsoft Defender Antivirus definitions and see of that solves the problem?

**Comment by marvellius** [comment] 2021-08-19 12:46
@nsc-jens This worked perfectly for me and I had the same issue. Thank you very much for pointing that out.

**Comment by Nnoggie** [comment] 2021-08-19 23:59
Windows Defender was causing problem of falsely flagging AddOn updates from curseforge as malware. This was an issue on Microsofts part with a faulty definition from Wednesday that has been since fixed. Downloading the newest definition will resolve the issue. Learn more here: https://www.microsoft.com/en-us/wdsi/defenderupdates

**Closed** 2021-08-21 01:01 UTC
